name:                consolation
version:             0.1.0.0
github:              "johncowie/consolation"
license:             BSD3
author:              "John Cowie"
maintainer:          "john.a.cowie@gmail.com"
copyright:           "2018 John Cowie"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/johncowie/consolation#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  consolation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - consolation
